name: watchos-sample

on:
  pull_request:
    paths:
    # Sources
    - 'FirebaseABTesting/**'
    - 'FirebaseDatabase/**'
    - 'FirebaseRemoteConfig/**'
    - 'FirebaseStorage/**'
    # Sample
    - 'Example/watchOSSample/**'
    # Firebase Podspec
    - 'Firebase.podspec'
    # This file
    - '.github/workflows/watchos-sample.yml'
    # Rebuild on Ruby infrastructure changes
    - 'Gemfile*'
  schedule:
    # Run every day at 10pm (PST) - cron uses UTC times
    - cron:  '0 6 * * *'

jobs:

  tv-sample-build-test:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Prereqs
      run: scripts/install_prereqs.sh WatchOSSample watchOS
    - name: Build
      run: ([ -z $plist_secret ] || scripts/build.sh WatchOSSample watchOS)
