osx_image: xcode10
language: objective-c
cache:
  - bundler
  - cocoapods

matrix:
  include:
    - podfile: ios/objc/Podfile
      env: 
        - LANGUAGE=ObjC
        - DIR=ios/objc
    - podfile: ios/swift/Podfile
      env: 
        - LANGUAGE=Swift
        - DIR=ios/swift
    - podfile: grow-ios-starter/objc-starter/Podfile
      env: 
        - LANGUAGE=ObjC
        - DIR=grow-ios-starter/objc-starter
    - podfile: grow-ios-starter/swift-starter/Podfile
      env: 
        - LANGUAGE=Swift
        - DIR=grow-ios-starter/swift-starter
    - podfile: ios-starter/objc-starter/Podfile
      env:
        - LANGUAGE=ObjC
        - DIR=ios-starter/objc-starter
      before_install:
        - bundle install
        - gem install xcpretty
        - cd ios-starter/objc-starter
        - bundle exec pod install --repo-update
        - cd -
    - podfile: ios-starter/swift-starter/Podfile
      env: 
        - LANGUAGE=Swift
        - DIR=ios-starter/swift-starter
      before_install:
        - bundle install
        - gem install xcpretty
        - cd ios-starter/swift-starter
        - bundle exec pod install --repo-update
        - cd -

before_install:
  - bundle install
  - gem install xcpretty
  - cd ios/$LANGUAGE
  - bundle exec pod install --repo-update
  - cp ../mock-GoogleService-Info.plist ./GoogleService-Info.plist
  - sed -i '' '/<key>BUNDLE_ID</{n;s/id/com.google.firebase.codelab.FriendlyChat'$LANGUAGE'/;}' GoogleService-Info.plist
  - sed -i '' 's/YOUR_REVERSED_CLIENT_ID/com.googleusercontent.apps.123456789000-hjugbg6ud799v4c49dim8ce2usclthar/' FriendlyChat"$LANGUAGE"/Info.plist
  - gem install xcodeproj
  - ruby ../info_script.rb $LANGUAGE
  - cd -

script: ./test.sh

branches:
  only:
    - master
