driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8080}]
    run_list:
    - recipe[apt::default]
  - name: ubuntu-12.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8081}]
    run_list:
    - recipe[apt::default]
  - name: ubuntu-10.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8082}]
    run_list:
    - recipe[apt::default]
  - name: debian-7.8
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8083}]
    run_list:
    - recipe[apt::default]
  - name: debian-6.0.10
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8084}]
    run_list:
    - recipe[apt::default]
  - name: freebsd-9.3
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8085}]
    run_list:
    - recipe[freebsd::portsnap]
  - name: freebsd-10.1
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8086}]
    run_list:
    - recipe[freebsd::portsnap]
  - name: centos-7.1
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8087}]
    run_list:
    - recipe[yum::default]
  - name: centos-6.6
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8088}]
    run_list:
    - recipe[yum::default]
  - name: centos-5.11
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8089}]
    run_list:
    - recipe[yum::default]
  - name: fedora-20
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8090}]
    run_list:
    - recipe[yum::default]
  - name: fedora-21
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8091}]
    run_list:
    - recipe[yum::default]

suites:
 - name: server_package
   run_list:
   - recipe[nagios::default]
   - recipe[nrpe::default]
   - recipe[nagios_test::default]
   - role[monitoring]
   attributes:
     nagios:
 - name: server_source
   run_list:
   - recipe[nagios::default]
   - recipe[nrpe::default]
   - recipe[nagios_test::default]
   - role[monitoring]
   attributes:
     nagios:
       server:
         install_method: 'source'
 - name: pagerduty
   run_list:
   - recipe[nagios::default]
   - recipe[nagios::pagerduty]
   - recipe[nrpe::default]
   - recipe[nagios_test::default]
   - role[monitoring]
   attributes:
     nagios:
       server:
         install_method: 'source'
       pagerduty:
         key: 'your_key_here_3eC2'
data_bags_path: test/data_bags
roles_path: test/roles
