AllCops:
  Exclude:
    - vendor/**/*

AlignParameters:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
NumericLiterals:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
PerceivedComplexity:
  Enabled: false
AbcSize:
  Enabled: false
